# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BlinkIDRN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BlinkIDRN
  pod 'PPBlinkID', '~> 4.4.0'

  target 'BlinkIDRN-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BlinkIDRNTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

